### ISSUE TITLE
Crashes when switching input?

### ISSUE THREAD

**Issue by hjf** [tomaskovacik/BK8000L#13]
Hello,
I'm using your library with the ROM image from https://github.com/tomaskovacik/kicad-library/blob/master/library/datasheet/F-6188_BK8000L/bins/firmware_serial.bin but when I change inputs (i want to try the line input) it seems to crash. It disconnects from the computer and I see the program restarting.
Does that version of the configuration support line input?

**Comment by tomaskovacik** [comment]
hello,
line input disables the whole BT chip, it is normal behaviour, after disconnecting AUX, BT module boots up the same way as after applying power.

**Comment by hjf** [comment]
Interesting, then what is the AUX input for then? is it for using the chip as an audio amplifier alone?
I guess that makes sense.

**Comment by tomaskovacik** [comment]
audio is routed to output pins but to be honest, I did not investigate it in detail.
