### ISSUE TITLE
Bk7252 application software setup Wi-Fi tests 

### ISSUE THREAD

**Issue by Ducomex** [tomaskovacik/BK8000L#14]
Hi dears.

I'm looking for an app at beken, to be able make Wi-Fi continuous test by RF cable.

It's necessary to get a certified from Brazil government (Anatel) they require wifi test to all products.

The chipset of beken Bk7252 is in a mini camera wifi.

Tks

![Screenshot_20220104-223224](https://user-images.githubusercontent.com/97136892/148146622-26fdbdfc-a8b8-4376-a9a0-8901fe19efd9.png)

![Screenshot_20220104-223240](https://user-images.githubusercontent.com/97136892/148146637-8df74d7f-892f-4251-b285-36e7e68ee78c.png)

![Screenshot_20220104-223309](https://user-images.githubusercontent.com/97136892/148146656-654b6635-1aac-4b11-a184-e45203495a80.png)

**Comment by tomaskovacik** [comment]
I have nothing to do with beken corp. cant help you, sorry
