### ISSUE TITLE
Arduino IDE compile problem

### ISSUE THREAD

**Issue by fendt126** [tomaskovacik/BK8000L#2]
Hi
I have error while compiling example code:

C:\Users\Krzysztof\Documents\Arduino\libraries\BK8000L-master\BK8000L.cpp:36:2: error: expected initializer before 'btSerial'

  btSerial->end();

  ^

C:\Users\Krzysztof\Documents\Arduino\libraries\BK8000L-master\BK8000L.cpp:37:1: error: expected declaration before '}' token

 }

**Comment by tomaskovacik** [comment]
missing {

thx for report!

t.
