### ISSUE TITLE
undocumented commands for BEKEN module BK8000L and BK3254

### ISSUE THREAD

**Issue by tomaskovacik** [tomaskovacik/BK8000L#6]
BK3254:
CMD+AUD+ENABLE+%d+%d"
CMD+AUD+CONF+%d
CMD+FLASH+AECIOCTL+%d+%d"
CMD+FAIL
CMD+OK
CMD+AUD+ENABLE+%d+%d
CMD+DUTTEST+CLOSE"
CMD+DUTTEST+OPEN"
CMD+SINWAVE+OPEN"
CMD+SINWAVE+CLOSE"
CMD+SINWAVE+CONF+%d+%d+%d"

bk8000L;
DUTTEST
OPEN
CLOSE
SINWAVE
CONF
FLASH
DEBUGSHOW
DEBUGENV
ENABLE
DISCONN
A2DP
AVRCP
REGNO
transaction label
PLAY
PAUSE
PREV
NEXT
FORWARD
REWIND
PAIR
ACCEPT
REJECT
HUNG
REDIAL
DTMF
IDLE
CHECK

**Comment by tomaskovacik** [comment]
so I try it on BK8000L and BK3254 modules without luck :(

EDIT:

my module is comunicating at 9600bps so default comunication speed in software did not work (115200)

trying it on serial, it actualy do something on BK8000L ... need more testing

**Comment by xandeerzz** [comment]
I confirm the EQ commands working on the BK8000L with EQ0-EQ4 Option and EQ enable. Each EQ is for a particular frequency from the table above. I boosted the low range and the ouput started distorting very bad. Everything with moderation(a few dB should be enough)

**Comment by tomaskovacik** [comment]
can you send what commands did you try?

what I can say:

bk8000L module:

this make module really quite:
CMD+AUD+CONF+1+1+1+18000+200+44100+200
CMD+AUD+ENABLE+1+1

for BK3254 it did not do anything

t.

**Comment by xandeerzz** [comment]
CMD+AUD+ENABLE+0+1
CMD+AUD+CONF+0+0+0+30000+70+44100+200
This commands sets the eq0 on, sets it as low-pass filter with a gain of 3dB, a center frequency of 70Hz, 44100 sample rate, and a bandwidth of 200Hz

**Comment by tomaskovacik** [comment]
this just make volume low on my module :/ did you have dump of your eeprom?

**Comment by xandeerzz** [comment]
It is the dump with the AT commands from the google group bk8000l

**Comment by johnyradio** [comment]
@xandeerzz Can you apply EQ while playing music?
What's your hardware connection? How is your BK8000L connected to your computer?
thx!

**Comment by niclas0219** [comment]
How are you guys applying the commands, for instance CMD+AUD+ENABLE+0+1 ? Over serial?
If I try AT+CMD+AUD+ENABLE+0+1 i get an "OK" in return from the chip but I don't really know if I can trust it because if i try "AT+CMD+XUD+XNABLE+0+1" i still get an OK. If i edit the word CMD i get no response at all. I'm using the BK8000L

**Comment by Largebytetechnology** [comment]
Could you please help me?
I've got the module with the BK3254 and wired it up via UART. If I turn the module on it sends a few lines out (for example BT_CN), but I can't get it to respond to any comands listed in the datasheet.
I don't know what I do wrong but I just want to rename my device.

**Comment by tomaskovacik** [comment]
please do not ask questions in issues regarding other problems, thx

I moved your question here: 

https://github.com/tomaskovacik/BK3254/issues/11
