### ISSUE TITLE
Is it possible to get metadata information like artist name/track name

### ISSUE THREAD

**Issue by namebufu** [tomaskovacik/BK8000L#8]

**Comment by tomaskovacik** [comment]
hello, please read datasheet before you ask question. But to answare it: unfortunetly no.

if you like it, go for microchip module BM20, library is in development here: https://github.com/tomaskovacik/arduino/tree/master/BM20stm32

module can by ordered directly from microchip for 8$ so no to expensive  and it is full featured module, devel boards are here: https://www.tindie.com/products/tomaskovacik/bm20-breadboard-adapter/



t.
